# Generated by Django 5.0.7 on 2025-12-08 19:16

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="api_token",
            field=models.CharField(
                default=devices.models.generate_api_token,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
