# Generated by Django 5.0.7 on 2025-12-09 11:43

import hashlib

from django.db import migrations, models


def populate_checksums(apps, schema_editor):
    DeviceFirmware = apps.get_model("devices", "DeviceFirmware")
    for firmware in DeviceFirmware.objects.all():
        firmware.checksum = (
            hashlib.sha256(firmware.content.encode("utf-8")).hexdigest()
            if firmware.content
            else ""
        )
        firmware.config_checksum = (
            hashlib.sha256(firmware.config.encode("utf-8")).hexdigest()
            if firmware.config
            else ""
        )
        firmware.save(update_fields=["checksum", "config_checksum"])


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_devicefirmware_devicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicefirmware",
            name="checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="devicefirmware",
            name="config",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicefirmware",
            name="config_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="devicefirmware",
            name="config_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.RunPython(populate_checksums, migrations.RunPython.noop),
    ]
