# Generated by Django 5.0.7 on 2025-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_devicefirmware_checksum_devicefirmware_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicelog",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="devicelog",
            name="firmware_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="devicelog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
