# Generated by Django 5.0.7 on 2025-12-09 13:48

import devices.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_devicelog_event_type_devicelog_firmware_version_and_more"),
        ("households", "0003_alter_building_address_alter_building_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="api_token",
            field=models.CharField(
                default=devices.models.generate_api_token,
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="توکن API",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="households.building",
                verbose_name="ساختمان",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین مشاهده"
            ),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="checksum",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="چک\u200cسام"
            ),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="config",
            field=models.TextField(blank=True, default="", verbose_name="پیکربندی"),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="config_checksum",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="چک\u200cسام پیکربندی"
            ),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="config_version",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="نسخه پیکربندی"
            ),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="content",
            field=models.TextField(verbose_name="محتوا"),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firmware",
                to="devices.device",
                verbose_name="دستگاه",
            ),
        ),
        migrations.AlterField(
            model_name="devicefirmware",
            name="version",
            field=models.CharField(max_length=50, verbose_name="نسخه"),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="زمان ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="devices.device",
                verbose_name="دستگاه",
            ),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="event_type",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="نوع رویداد"
            ),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="firmware_version",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="نسخه میان\u200cافزار",
            ),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="level",
            field=models.CharField(blank=True, max_length=20, verbose_name="سطح"),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="message",
            field=models.TextField(verbose_name="پیام"),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
        ),
    ]
