# Generated by Django 5.0.7 on 2025-12-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0002_building"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="building",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="household",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="households",
                to="households.building",
                verbose_name="ساختمان",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="households",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سرپرست",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="allowed_from_time",
            field=models.TimeField(verbose_name="زمان شروع مجاز"),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="allowed_to_time",
            field=models.TimeField(verbose_name="زمان پایان مجاز"),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="households.household",
                verbose_name="خانوار",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
