# Generated by Django 5.0.7 on 2025-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doorcommand",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
