# Generated by Django 5.0.7 on 2025-12-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_doorcommand_expired"),
        ("devices", "0007_alter_device_api_token_alter_device_building_and_more"),
        ("households", "0003_alter_building_address_alter_building_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="households.household",
                verbose_name="خانوار",
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="reason",
            field=models.TextField(blank=True, verbose_name="دلیل"),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("denied", "Denied")],
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="devices.device",
                verbose_name="دستگاه",
            ),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="executed",
            field=models.BooleanField(default=False, verbose_name="اجرا شده"),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان اجرا"),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="expired",
            field=models.BooleanField(default=False, verbose_name="منقضی شده"),
        ),
        migrations.AlterField(
            model_name="doorcommand",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="door_commands",
                to=settings.AUTH_USER_MODEL,
                verbose_name="درخواست\u200cدهنده",
            ),
        ),
    ]
